# Generated by Django 3.1.1 on 2020-09-23 13:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='nome',
            field=models.CharField(max_length=100, unique=True, verbose_name='nome'),
        ),
        migrations.AlterField(
            model_name='livro',
            name='preco',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.01, message='Preço deve ser maior que 0.')], verbose_name='preco'),
        ),
        migrations.AlterField(
            model_name='livro',
            name='quatidade_de_paginas',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0.01, message='Quantidade de páginas deve ser maior que 0.')], verbose_name='quantidade_de_paginas'),
        ),
    ]
