# Generated by Django 3.1.1 on 2020-09-29 19:00

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0003_auto_20200923_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='preco',
            field=models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.01'), message='Preço deve ser maior que 0.')], verbose_name='preco'),
        ),
        migrations.AlterField(
            model_name='livro',
            name='quantidade_de_paginas',
            field=models.PositiveIntegerField(verbose_name='quantidade_de_paginas'),
        ),
    ]
